import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import QueryClientProvider from './QueryClientProvider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin=""
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css"
        />
      </head> */}
      <body>
        <Toaster position="top-center" richColors />
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  )
}
